name: CI (bors)

on:
  push:
    branches:
      - auto-libc
      - try

jobs:
  build_channels_linux:
    name: Build Channels Linux
    runs-on: ubuntu-18.04
    env:
      OS: linux
    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        toolchain: [
          nightly,
        ]
    steps:
      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        run: TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/install-rust.sh
      - name: Execute build.sh
        run: LIBC_CI=1 TOOLCHAIN=${{ matrix.toolchain }} sh ./ci/build.sh


  # These jobs doesn't actually test anything, but they're only used to tell
  # bors the build completed, as there is no practical way to detect when a
  # workflow is successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  end_success:
    name: bors build finished
    if: github.event.pusher.name == 'bors' && success()
    runs-on: ubuntu-18.04
    needs: [
      build_channels_linux,
    ]

    steps:
      - name: Mark the job as successful
        run: exit 0

  end_failure:
    name: bors build finished
    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
    runs-on: ubuntu-18.04
    needs: [
      build_channels_linux,
    ]

    steps:
      - name: Mark the job as a failure
        run: exit 1
